version: 2

models:
  - name: test_concat
    tests:
      - equal_value:
          actual: '`Two_text_fields`'
          expected: '`Two_text_fields_expected`'
      - equal_value:
          actual: '`One_null`'
          expected: '`One_null_expected`'

  - name: test_charindex
    tests:
      - equal_value:
          actual: '`Find_basic_scenario`'
          expected: '`Find_basic_scenario_expected`'
      - equal_value:
          actual: '`Find_first_of_multiple_occurrences`'
          expected: '`Find_first_of_multiple_occurrences_expected`'
      - equal_value:
          actual: '`Find_first_space`'
          expected: '`Find_first_space_expected`'
      - equal_value:
          actual: '`Find_with_start_location`'
          expected: '`Find_with_start_location_expected`'
      - equal_value:
          actual: '`Find_non_occurring_value`'
          expected: '`Find_non_occurring_value_expected`'
      - equal_value:
          actual: '`Find_empty_value`'
          expected: '`Find_empty_value_expected`'
      - equal_value:
          actual: '`Find_null_value`'
          expected: '`Find_null_value_expected`'

  - name: test_to_timestamp
    tests:
      - equal_value:
          actual: '`timestamp_date`'
          expected: '`timestamp_date_expected`'
      - equal_value:
          actual: '`timestamp_datetime`'
          expected: '`timestamp_datetime_expected`'
      - equal_value:
          actual: '`timestamp_datetime_ms`'
          expected: '`timestamp_datetime_ms_expected`'
      - equal_value:
          actual: '`timestamp_datetime_ms4`'
          expected: '`timestamp_datetime_ms4_expected`'
      - equal_value:
          actual: '`timestamp_time`'
          expected: '`timestamp_time_expected`'
      - equal_value:
          actual: '`null_value`'
          expected: '`null_value_expected`'

  - name: test_dateadd
    tests:
      - equal_value:
          actual: '`add_milliseconds`'
          expected: '`add_milliseconds_expected`'
      - equal_value:
          actual: '`add_seconds`'
          expected: '`add_seconds_expected`'
      - equal_value:
          actual: '`add_minutes`'
          expected: '`add_minutes_expected`'
      - equal_value:
          actual: '`add_hours`'
          expected: '`add_hours_expected`'
      - equal_value:
          actual: '`add_days`'
          expected: '`add_days_expected`'
      - equal_value:
          actual: '`add_weeks`'
          expected: '`add_weeks_expected`'
      - equal_value:
          actual: '`add_months`'
          expected: '`add_months_expected`'
      - equal_value:
          actual: '`add_quarters`'
          expected: '`add_quarters_expected`'
      - equal_value:
          actual: '`add_years`'
          expected: '`add_years_expected`'
      - equal_value:
          actual: '`add_30_days_in_days`'
          expected: '`add_30_days_in_days_expected`'
      - equal_value:
          actual: '`add_30_days_in_seconds`'
          expected: '`add_30_days_in_seconds_expected`'
      - equal_value:
          actual: '`add_bigint`'
          expected: '`add_bigint_expected`'
      - equal_value:
          actual: '`add_bigint_30_days`'
          expected: '`add_bigint_30_days_expected`'
      - equal_value:
          actual: '`add_to_null_value`'
          expected: '`add_to_null_value_expected`'

  - name: test_stddev
    tests:
    - equal_value:
        actual: '`stddev_actual`'
        expected: '`stddev_expected`'
    - equal_value:
        actual: '`stddev_with_null_values_actual`'
        expected: '`stddev_with_null_values_expected`'
