version: 2

models:
  - name: test_concat
    data_tests:
      - equal_value:
          actual: '"Two_text_fields"'
          expected: '"Two_text_fields_expected"'
      - equal_value:
          actual: '"One_null"'
          expected: '"One_null_expected"'

  - name: test_charindex
    data_tests:
      - equal_value:
          actual: '"Find_basic_scenario"'
          expected: '"Find_basic_scenario_expected"'
      - equal_value:
          actual: '"Find_first_of_multiple_occurrences"'
          expected: '"Find_first_of_multiple_occurrences_expected"'
      - equal_value:
          actual: '"Find_first_space"'
          expected: '"Find_first_space_expected"'
      - equal_value:
          actual: '"Find_with_start_location"'
          expected: '"Find_with_start_location_expected"'
      - equal_value:
          actual: '"Find_non_occurring_value"'
          expected: '"Find_non_occurring_value_expected"'
      - equal_value:
          actual: '"Find_empty_value"'
          expected: '"Find_empty_value_expected"'
      - equal_value:
          actual: '"Find_null_value"'
          expected: '"Find_null_value_expected"'

  - name: test_to_timestamp
    data_tests:
      - equal_value:
          actual: '"timestamp_date"'
          expected: '"timestamp_date_expected"'
      - equal_value:
          actual: '"timestamp_datetime"'
          expected: '"timestamp_datetime_expected"'
      - equal_value:
          actual: '"timestamp_datetime_ms"'
          expected: '"timestamp_datetime_ms_expected"'
      - equal_value:
          actual: '"timestamp_datetime_ms4"'
          expected: '"timestamp_datetime_ms4_expected"'
      - equal_value:
          actual: '"timestamp_time"'
          expected: '"timestamp_time_expected"'
      - equal_value:
          actual: '"null_value"'
          expected: '"null_value_expected"'

  - name: test_dateadd
    data_tests:
      - equal_value:
          actual: '"add_milliseconds"'
          expected: '"add_milliseconds_expected"'
      - equal_value:
          actual: '"add_seconds"'
          expected: '"add_seconds_expected"'
      - equal_value:
          actual: '"add_minutes"'
          expected: '"add_minutes_expected"'
      - equal_value:
          actual: '"add_hours"'
          expected: '"add_hours_expected"'
      - equal_value:
          actual: '"add_days"'
          expected: '"add_days_expected"'
      - equal_value:
          actual: '"add_weeks"'
          expected: '"add_weeks_expected"'
      - equal_value:
          actual: '"add_months"'
          expected: '"add_months_expected"'
      - equal_value:
          actual: '"add_quarters"'
          expected: '"add_quarters_expected"'
      - equal_value:
          actual: '"add_years"'
          expected: '"add_years_expected"'
      - equal_value:
          actual: '"add_30_days_in_days"'
          expected: '"add_30_days_in_days_expected"'
      - equal_value:
          actual: '"add_30_days_in_seconds"'
          expected: '"add_30_days_in_seconds_expected"'
      - equal_value:
          actual: '"add_bigint"'
          expected: '"add_bigint_expected"'
      - equal_value:
          actual: '"add_bigint_30_days"'
          expected: '"add_bigint_30_days_expected"'
      - equal_value:
          actual: '"add_double_days"'
          expected: '"add_double_days_expected"'
      - equal_value:
          actual: '"add_to_null_value"'
          expected: '"add_to_null_value_expected"'

  - name: test_stddev
    data_tests:
    - equal_value:
        actual: '"stddev_actual"'
        expected: '"stddev_expected"'
    - equal_value:
        actual: '"stddev_with_null_values_actual"'
        expected: '"stddev_with_null_values_expected"'

  - name: test_datediff
    data_tests:
    - equal_value:
        actual: '"Year"'
        expected: '"Year_expected"'
    - equal_value:
        actual: '"Quarter"'
        expected: '"Quarter_expected"'
    - equal_value:
        actual: '"Month"'
        expected: '"Month_expected"'
    - equal_value:
        actual: '"Week_saturday_to_sunday"'
        expected: '"Week_saturday_to_sunday_expected"'
    - equal_value:
        actual: '"Week_sunday_to_saturday"'
        expected: '"Week_sunday_to_saturday_expected"'
    - equal_value:
        actual: '"Day"'
        expected: '"Day_expected"'
    - equal_value:
        actual: '"Hour"'
        expected: '"Hour_expected"'
    - equal_value:
        actual: '"Minute"'
        expected: '"Minute_expected"'
    - equal_value:
        actual: '"Second"'
        expected: '"Second_expected"'
    - equal_value:
        actual: '"Millisecond"'
        expected: '"Millisecond_expected"'

  - name: test_diff_weekdays
    data_tests:
    - equal_value:
        actual: '"Two_weekends"'
        expected: '"Two_weekends_expected"'
    - equal_value:
        actual: '"One_half_weekends"'
        expected: '"One_half_weekends_expected"'
    - equal_value:
        actual: '"One_weekend"'
        expected: '"One_weekend_expected"'
    - equal_value:
        actual: '"One_weekend_end"'
        expected: '"One_weekend_end_expected"'
    - equal_value:
        actual: '"Half_weekend"'
        expected: '"Half_weekend_expected"'
    - equal_value:
        actual: '"Start_weekend"'
        expected: '"Start_weekend_expected"'
    - equal_value:
        actual: '"Start_half_weekend"'
        expected: '"Start_half_weekend_expected"'
    - equal_value:
        actual: '"Only_weekend"'
        expected: '"Only_weekend_expected"'

  - name: test_json
    data_tests:
    - equal_value:
        actual: '"One_level_field"'
        expected: '"One_level_field_expected"'
    - equal_value:
        actual: '"Two_level_field"'
        expected: '"Two_level_field_expected"'

  - name: test_union_relations
    data_tests:
    - equal_value:
        actual: '"Column_A"'
        expected: '"Column_A_Expected"'
    - equal_value:
        actual: '"Column_B"'
        expected: '"Column_B_Expected"'
    - equal_value:
        actual: '"Column_C"'
        expected: '"Column_C_Expected"'
    - equal_value:
        actual: '"Column_D"'
        expected: '"Column_D_Expected"'
    - equal_value:
        actual: '"Column_E"'
        expected: '"Column_E_Expected"'
    - equal_value:
        actual: '"Column_F"'
        expected: '"Column_F_Expected"'
