version: 2

sources:
  - name: sources
    schema: "{{ var('schema_sources', target.schema) }}"
    tables:
      - name: input_data_1
        columns:
          - name: RN
          - name: Column_A
          - name: Column_B
          - name: Column_C
      - name: input_data_2
        columns:
          - name: RN
          - name: Column_C
          - name: Column_E
          - name: Column_F
          - name: Column_A
      - name: input_data_3
        columns:
          - name: RN
          - name: Column_B
          - name: Column_C
          - name: Column_F
          - name: Column_G
      - name: union_data
        columns:
          - name: RN
          - name: Column_A
          - name: Column_B
          - name: Column_C
          - name: Column_E
          - name: Column_F
          - name: Column_G
    quoting:
      database: true
      schema: true
      identifier: true
